services:
  - type: web
    name: veritas-api
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: OPENAI_KEY
        sync: false
      - key: SERPER_KEY
        sync: false
      - key: TAVILY_KEY
        sync: false
